### ISSUE TITLE
Search by id 

### ISSUE THREAD

**Issue by badjoras7** [cytoscape/cytoscape.js-leaflet#1]
Hello,

Thank you for your work @maxkfranz, do you know if is possible to use this [https://github.com/stefanocudini/leaflet-search](https://github.com/stefanocudini/leaflet-search) side-by-side cytoscape.js-leaflet, to search for id?

Regards

**Comment by maxkfranz** [comment]
You're welcome to experiment with that extension and report your results here.  If you like, you can make a pull request with a demo for that to help others out
